---
- debug:
    var: hostvars

- name: Parse bgp summary
  ansible.utils.cli_parse:
    command: "show bgp summary"
    parser:
      name: ansible.netcommon.pyats
    set_fact: bgp_summary
  ignore_errors: yes

- include_tasks: includes/health_checks/{{ ansible_network_os.split('.')[2] }}.yaml

- name: "{{ ansible_network_os.split('.')[2] }}"
  debug:
    var: bgp_health


- include: includes/write_to_file.yaml
